#!/usr/bin/env python3

import argparse
import subprocess
import json
import os
from base64 import standard_b64decode, standard_b64encode
import shutil

# Pare arguments passed in via command line
parser = argparse.ArgumentParser(description='Process some options')
parser.add_argument('--namespace', '-n', dest="namespace", help='specify a Kubernetes namespace')
parser.add_argument('name', type=str, help='the secret name')
args = parser.parse_args()

# Set the important variables
namespace = args.namespace
secret_name = args.name

# Use kubectl, the Kubernetes CLI, to get the specified secret
result = subprocess.run(['kubectl', 'get', 'secret', '-n', namespace, secret_name, '-o', 'json'],
                        stdout=subprocess.PIPE)

# Load the JSON file, capture the data attribute we care about
res = json.loads(result.stdout.decode('utf-8'))
data = res.get("data", {})
keys = [key for key in data]

os.makedirs(".__temp__/", exist_ok=True)

EXIT_EDIT = False
MAKE_CHANGES = True
while not EXIT_EDIT:
    i = input("Please choose what to edit: \n" +
              "".join(["%d) %s\n" % (index + 1, key) for index, key in enumerate(keys)]) +
              "%d) ADD\n" % (len(keys) + 1) +
              "%d) CANCEL\n" % (len(keys) + 2) +
              "%d) DONE\n" % (len(keys) + 3))

    if not i.isdigit() or int(i) < 1:
        print("Please enter a digit!\n")
        continue
    else:
        i = int(i)
        if i == (len(keys) + 1):  # ADD
            name = input("Please enter the name of new file/literal: ")
            keys.append(name)
            filename = ".__temp__/__temp__%s" % name
        elif i == (len(keys) + 2):  # CANCEL
            EXIT_EDIT = True
            MAKE_CHANGES = False
            continue
        elif i == (len(keys) + 3):  # DONE
            EXIT_EDIT = True
            continue
        else:
            try:
                name = keys[i - 1]  # SELECTION MADE
                filename = ".__temp__/__temp__%s" % name
                with open(filename, 'w') as f:
                    f.write(standard_b64decode(data[name]).decode("utf-8"))
            except IndexError:
                print("Please select a valid number!\n")
                continue

        a = subprocess.run(['vim', filename])

        with open(filename, 'r') as f:
            contents = f.read().rstrip()
            if len(contents) == 0:
                del res["data"][name]
                delIndex = keys.index(name)
                keys.pop(delIndex)
            else:
                res["data"][name] = standard_b64encode(bytes(contents, 'utf-8')).decode("utf-8")

if MAKE_CHANGES:
    with open(".__temp__/__temp__.json", "w") as w:
        w.write(json.dumps(res))
    subprocess.run(["kubectl", "apply", "-f", ".__temp__/__temp__.json"])

shutil.rmtree('.__temp__')
